/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FabricaEntityManager;
import java.awt.EventQueue;
import java.beans.Beans;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.persistence.RollbackException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Bebida;
import model.BebidaUtilizada;
import model.Carne;
import model.Churrasco;
import model.Convidado;

/**
 *
 * @author cadilhe
 */
public class JCadChurrasco extends JPanel {

    public JCadChurrasco() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = FabricaEntityManager.getEntityManagerFactory().createEntityManager();
        queryChurrasco = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Churrasco c");
        listChurrascos = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryChurrasco.getResultList());
        queryConvidado = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("select c from Convidado c");
        listConvidados = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryConvidado.getResultList());
        queryBebida = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Bebida b");
        listBebidas = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryBebida.getResultList());
        queryCarne = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Carne c");
        listCarnes = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryCarne.getResultList());
        jpnButtons = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnChurrasco = new javax.swing.JPanel();
        lblIdchurrasco = new javax.swing.JLabel();
        txtIdchurrasco = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        ftxtData = new javax.swing.JFormattedTextField();
        ftxtHora = new javax.swing.JFormattedTextField();
        timeRenderer1 = new util.TimeRenderer();
        scrollPaneChurrasco = new javax.swing.JScrollPane();
        tblChurrascos = new javax.swing.JTable();
        jpnConvidados = new javax.swing.JPanel();
        lblSelecione = new javax.swing.JLabel();
        cbxConvidados = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConvidados = new javax.swing.JTable();
        btnRemoveConvidado = new javax.swing.JButton();
        btnAddConvidado = new javax.swing.JButton();
        jpnBebidas = new javax.swing.JPanel();
        lblSelectBebida = new javax.swing.JLabel();
        cbxBebidas = new javax.swing.JComboBox<>();
        lblQtde = new javax.swing.JLabel();
        ftxtQtde = new javax.swing.JFormattedTextField();
        lblPreco = new javax.swing.JLabel();
        jftxtPriceBebida = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBebidas = new javax.swing.JTable();
        btnRemoveBebida = new javax.swing.JButton();
        btnAddBebida = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSelectCarne = new javax.swing.JLabel();
        cbxCarnes = new javax.swing.JComboBox<>();
        lblQtde1 = new javax.swing.JLabel();
        ftxtQtdeCarne = new javax.swing.JFormattedTextField();
        jftxtPriceCarne = new javax.swing.JFormattedTextField();
        lblPriceCarne = new javax.swing.JLabel();
        btnRemoveCarne = new javax.swing.JButton();
        btnAddCarne = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCarnes = new javax.swing.JTable();
        precoRenderer1 = new util.PrecoRenderer();
        jlbllogo = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/churrasco_cancel.png"))); // NOI18N
        refreshButton.setText("Cancelar");
        refreshButton.addActionListener(formListener);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/churrasco_add.png"))); // NOI18N
        newButton.setText("Novo");
        newButton.addActionListener(formListener);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/churrasco_save.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(formListener);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/churrasco_remove.png"))); // NOI18N
        deleteButton.setText("Excluir");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        javax.swing.GroupLayout jpnButtonsLayout = new javax.swing.GroupLayout(jpnButtons);
        jpnButtons.setLayout(jpnButtonsLayout);
        jpnButtonsLayout.setHorizontalGroup(
            jpnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        jpnButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, newButton, refreshButton, saveButton});

        jpnButtonsLayout.setVerticalGroup(
            jpnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addGap(8, 8, 8)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        lblIdchurrasco.setText("Código:");

        txtIdchurrasco.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idchurrasco}"), txtIdchurrasco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);

        lblData.setText("Data:");

        lblHora.setText("Hora:");

        lblLocal.setText("Local:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.local}"), txtLocal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtLocal, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ftxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.data}"), ftxtData, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ftxtData, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        ftxtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.hora}"), ftxtHora, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), ftxtHora, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listChurrascos, tblChurrascos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idchurrasco}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${local}"));
        columnBinding.setColumnName("Local");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${data}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hora}"));
        columnBinding.setColumnName("Hora");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblChurrascos.addMouseListener(formListener);
        scrollPaneChurrasco.setViewportView(tblChurrascos);
        if (tblChurrascos.getColumnModel().getColumnCount() > 0) {
            tblChurrascos.getColumnModel().getColumn(3).setCellRenderer(timeRenderer1);
        }

        javax.swing.GroupLayout jpnChurrascoLayout = new javax.swing.GroupLayout(jpnChurrasco);
        jpnChurrasco.setLayout(jpnChurrascoLayout);
        jpnChurrascoLayout.setHorizontalGroup(
            jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChurrascoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneChurrasco, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(jpnChurrascoLayout.createSequentialGroup()
                        .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdchurrasco)
                            .addComponent(lblData)
                            .addComponent(lblHora)
                            .addComponent(lblLocal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocal)
                            .addComponent(ftxtHora, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdchurrasco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftxtData, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnChurrascoLayout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(timeRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );
        jpnChurrascoLayout.setVerticalGroup(
            jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChurrascoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdchurrasco)
                    .addComponent(txtIdchurrasco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHora)
                    .addComponent(ftxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(scrollPaneChurrasco, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnChurrascoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnChurrascoLayout.createSequentialGroup()
                    .addContainerGap(255, Short.MAX_VALUE)
                    .addComponent(timeRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(131, 131, 131)))
        );

        jTabbedPane1.addTab("Dados do Churrasco", jpnChurrasco);

        lblSelecione.setText("Selecione o convidado");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listConvidados, cbxConvidados);
        bindingGroup.addBinding(jComboBoxBinding);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.convidados}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, eLProperty, tblConvidados);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${churrascos}"));
        columnBinding.setColumnName("Churrascos");
        columnBinding.setColumnClass(java.util.List.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblConvidados);

        btnRemoveConvidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_remove.png"))); // NOI18N
        btnRemoveConvidado.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblConvidados, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnRemoveConvidado, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnRemoveConvidado.addActionListener(formListener);

        btnAddConvidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_save.png"))); // NOI18N
        btnAddConvidado.setText("Convidar");
        btnAddConvidado.addActionListener(formListener);

        javax.swing.GroupLayout jpnConvidadosLayout = new javax.swing.GroupLayout(jpnConvidados);
        jpnConvidados.setLayout(jpnConvidadosLayout);
        jpnConvidadosLayout.setHorizontalGroup(
            jpnConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConvidadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jpnConvidadosLayout.createSequentialGroup()
                        .addComponent(lblSelecione)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnConvidadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                        .addComponent(btnRemoveConvidado)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddConvidado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnConvidadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnConvidadosLayout.setVerticalGroup(
            jpnConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConvidadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxConvidados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnConvidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveConvidado)
                    .addComponent(btnAddConvidado))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Convidados", jpnConvidados);

        lblSelectBebida.setText("Bebida");

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listBebidas, cbxBebidas);
        bindingGroup.addBinding(jComboBoxBinding);

        lblQtde.setText("Quantidade");

        ftxtQtde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lblPreco.setText("Preço");

        jftxtPriceBebida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jftxtPriceBebida.addFocusListener(formListener);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.bebidasUtilizadas}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, eLProperty, tblBebidas);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idBebidaUtilizada}"));
        columnBinding.setColumnName("Id Bebida Utilizada");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bebida}"));
        columnBinding.setColumnName("Bebida");
        columnBinding.setColumnClass(model.Bebida.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoTotal}"));
        columnBinding.setColumnName("Preco Total");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane4.setViewportView(tblBebidas);

        btnRemoveBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_remove.png"))); // NOI18N
        btnRemoveBebida.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblBebidas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnRemoveBebida, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnRemoveBebida.addActionListener(formListener);

        btnAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_add.png"))); // NOI18N
        btnAddBebida.setText("Adicionar");
        btnAddBebida.addActionListener(formListener);

        javax.swing.GroupLayout jpnBebidasLayout = new javax.swing.GroupLayout(jpnBebidas);
        jpnBebidas.setLayout(jpnBebidasLayout);
        jpnBebidasLayout.setHorizontalGroup(
            jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBebidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(jpnBebidasLayout.createSequentialGroup()
                        .addGroup(jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectBebida)
                            .addComponent(cbxBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnBebidasLayout.createSequentialGroup()
                                .addComponent(lblQtde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBebidasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBebidasLayout.createSequentialGroup()
                                .addComponent(lblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxtPriceBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBebidasLayout.createSequentialGroup()
                                .addComponent(btnRemoveBebida)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddBebida)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnBebidasLayout.setVerticalGroup(
            jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectBebida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtde)
                    .addComponent(ftxtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco)
                    .addComponent(jftxtPriceBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveBebida)
                    .addComponent(btnAddBebida))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bebidas", jpnBebidas);

        lblSelectCarne.setText("Carne");

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listCarnes, cbxCarnes);
        bindingGroup.addBinding(jComboBoxBinding);

        lblQtde1.setText("Quantidade");

        ftxtQtdeCarne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jftxtPriceCarne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jftxtPriceCarne.addFocusListener(formListener);

        lblPriceCarne.setText("Preço");

        btnRemoveCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_remove.png"))); // NOI18N
        btnRemoveCarne.setText("Remover");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblCarnes, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnRemoveCarne, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnAddCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/op_add.png"))); // NOI18N
        btnAddCarne.setText("Adicionar");
        btnAddCarne.addActionListener(formListener);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.carnesUtilizadas}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblChurrascos, eLProperty, tblCarnes);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCarneUtilizada}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${carne}"));
        columnBinding.setColumnName("Carne");
        columnBinding.setColumnClass(model.Carne.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${carne.preco}"));
        columnBinding.setColumnName("Preço");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidade}"));
        columnBinding.setColumnName("Quantidade");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoTotal}"));
        columnBinding.setColumnName("Preço Total");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane5.setViewportView(tblCarnes);
        if (tblCarnes.getColumnModel().getColumnCount() > 0) {
            tblCarnes.getColumnModel().getColumn(4).setCellRenderer(precoRenderer1);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSelectCarne)
                                    .addComponent(cbxCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblQtde1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftxtQtdeCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPriceCarne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftxtPriceCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(precoRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveCarne)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCarne)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectCarne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtde1)
                    .addComponent(ftxtQtdeCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceCarne)
                    .addComponent(jftxtPriceCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precoRenderer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRemoveCarne)
                        .addComponent(btnAddCarne)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Carnes", jPanel1);

        jlbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/churrasco_cadastro.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbllogo)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbllogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jTabbedPane1)))
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == refreshButton) {
                JCadChurrasco.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                JCadChurrasco.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                JCadChurrasco.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                JCadChurrasco.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == btnRemoveConvidado) {
                JCadChurrasco.this.btnRemoveConvidadoActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddConvidado) {
                JCadChurrasco.this.btnAddConvidadoActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddBebida) {
                JCadChurrasco.this.btnAddBebidaActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddCarne) {
                JCadChurrasco.this.btnAddCarneActionPerformed(evt);
            }
            else if (evt.getSource() == btnRemoveBebida) {
                JCadChurrasco.this.btnRemoveBebidaActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == jftxtPriceBebida) {
                JCadChurrasco.this.jftxtPriceBebidaFocusLost(evt);
            }
            else if (evt.getSource() == jftxtPriceCarne) {
                JCadChurrasco.this.jftxtPriceCarneFocusLost(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == tblChurrascos) {
                JCadChurrasco.this.tblChurrascosMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = queryChurrasco.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        listChurrascos.clear();
        listChurrascos.addAll(data);

        // Oculta as abas de JTabbedPane
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        // Mensagem de confirmaçao de exclusao de item. 
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

            // Se a opçao do usuário for YES, executar os comandos abaixo.
            int[] selected = tblChurrascos.getSelectedRows();
            List<model.Churrasco> toRemove = new ArrayList<model.Churrasco>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                model.Churrasco c = listChurrascos.get(tblChurrascos.convertRowIndexToModel(selected[idx]));
                toRemove.add(c);
                entityManager.remove(c);
            }
            listChurrascos.removeAll(toRemove);

            saveButton.doClick();

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        model.Churrasco c = new model.Churrasco();
        entityManager.persist(c);
        listChurrascos.add(c);
        int row = listChurrascos.size() - 1;
        tblChurrascos.setRowSelectionInterval(row, row);
        tblChurrascos.scrollRectToVisible(tblChurrascos.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
            // Janela para confirmar o Salvamento
            JOptionPane.showMessageDialog(null, "Registro atualizado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<model.Churrasco> merged = new ArrayList<model.Churrasco>(listChurrascos.size());
            for (model.Churrasco c : listChurrascos) {
                merged.add(entityManager.merge(c));
            }
            listChurrascos.clear();
            listChurrascos.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void btnAddConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConvidadoActionPerformed

        // Este método faz o relacionamento muito para muitos: adiciona Convidado a Churrasco e Churraco a Convidado
        int rowChurrasco = tblChurrascos.getSelectedRow();
        Churrasco churrasco = listChurrascos.get(rowChurrasco);
        Convidado convidado = (Convidado) cbxConvidados.getSelectedItem();
        churrasco.addConvidado(convidado);
        convidado.addChurrasco(churrasco);

        int ultimaLinhaConvidado = churrasco.sizeOfConvidado() - 1;
        tblConvidados.setRowSelectionInterval(ultimaLinhaConvidado, ultimaLinhaConvidado);
        tblConvidados.scrollRectToVisible(tblConvidados.getCellRect(ultimaLinhaConvidado, 0, true));

        atualizarTabelas(rowChurrasco);

        // saveButton.doClick();
    }//GEN-LAST:event_btnAddConvidadoActionPerformed

    private void atualizarTabelas(int rowChurrasco) {
        tblChurrascos.clearSelection(); // limpa a tabela de churrascos
        if (tblChurrascos.getRowCount() > 0) {
            int ultima = tblChurrascos.getRowCount() - 1;
            tblChurrascos.setRowSelectionInterval(0, 0);
            tblChurrascos.setRowSelectionInterval(ultima, ultima);
        }
        // Este código serve para manter a última linha da tabela selecioanada
        tblChurrascos.setRowSelectionInterval(rowChurrasco, rowChurrasco);
    }

    private void btnRemoveConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveConvidadoActionPerformed
        // TODO add your handling code here: 
        /*
        * Método para remover a associação entre o convidado e o churrasco, 
        para isso será necessário obter o objeto churrasco selecionado na JTable o convidado selecionado na outra JTable, 
        após chamaremos os métodos removeChurrasco e removeConvidado para destruir associação entre os objetos.
         */

        // 0 = Botao 1 YES, 1 = Botao 2 NO
        if (JOptionPane.showConfirmDialog(null, "Deseja remover convidado do Churrasco?", "Confirmaçao",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {

            // Obtém o Churrasco
            int churrascoSelecionado = tblChurrascos.getSelectedRow();
            Churrasco churrasco = listChurrascos.get(churrascoSelecionado);
//            
            // Obtém o convidado do Churrasco
            int convidadoSelecionado = tblConvidados.getSelectedRow();
            Convidado convidado = churrasco.getConvidado(convidadoSelecionado);

            churrasco.removeConvidado(convidado);
            convidado.removeChurrasco(churrasco);

            atualizarTabelas(churrascoSelecionado);

            // saveButton.doClick();
        }

    }//GEN-LAST:event_btnRemoveConvidadoActionPerformed

    private void jftxtPriceBebidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftxtPriceBebidaFocusLost
        // TODO add your handling code here:
        // String valor será obtido do campo digitado
        String sv = jftxtPriceBebida.getText();
        // Faz as devidas substituiçoes e limpeza no texto obtido do usuário 
        String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        // Um novo objeto da classe BigDecimal é instanciado com o valor da String limpa
        BigDecimal valor = new BigDecimal(vsf);
        // Formataçao da moeda para o novo local instanciado com o parametro pt.BR
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorFormatado = nf.format(valor);
        jftxtPriceBebida.setText(valorFormatado);

//        int index = tblBebidas.getSelectedRow();
//        Bebida b = listBebidas.get(index);
//        // passando o valor já como BigDecimal
//        b.setPreco(valor);
    }//GEN-LAST:event_jftxtPriceBebidaFocusLost

    private void btnAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBebidaActionPerformed
        // TODO add your handling code here:

        BebidaUtilizada bebidaUtilizada = new BebidaUtilizada();

        // Obtem bebida selecionada do Combobox com a lista de bebidas
        Bebida bebida = (Bebida) cbxBebidas.getSelectedItem();

        // Conversoes de tipos e atribuiçao de valores para cálculo de Preço Total
        Long quantidade = (Long) ftxtQtde.getValue();
        String svl = jftxtPriceBebida.getValue().toString();
        BigDecimal precoUnitario = new BigDecimal(svl);

        // Associaçao entre Churrasco e Bebida Utilizada. 
        bebidaUtilizada.setBebida(bebida);
        bebidaUtilizada.setPrecoItem(precoUnitario);
        bebidaUtilizada.setQuantidade(quantidade.floatValue());

        // Pega a linha selecionanda da tabela Churrasco e atribui o seu valor ao objeto churrasco alvo
        int linhaChurrasco = tblChurrascos.getSelectedRow();
        Churrasco churrasco = listChurrascos.get(linhaChurrasco);

        // Adiciona bebida ao objeto churrasco
        churrasco.addBebidaUtilizada(bebidaUtilizada);
        bebidaUtilizada.setChurrasco(churrasco);

        entityManager.persist(bebidaUtilizada);

        atualizarTabelas(linhaChurrasco);

        // saveButton.doClick();

    }//GEN-LAST:event_btnAddBebidaActionPerformed

    private void jftxtPriceCarneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftxtPriceCarneFocusLost
        // TODO add your handling code here:
        // String valor será obtido do campo digitado
        String sv = jftxtPriceCarne.getText();
        // Faz as devidas substituiçoes e limpeza no texto obtido do usuário 
        String vsf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        // Um novo objeto da classe BigDecimal é instanciado com o valor da String limpa
        BigDecimal valor = new BigDecimal(vsf);
        // Formataçao da moeda para o novo local instanciado com o parametro pt.BR
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorFormatado = nf.format(valor);
        jftxtPriceCarne.setText(valorFormatado);

        int index = tblCarnes.getSelectedRow();
        Carne c = listCarnes.get(index);
        // passando o valor já como BigDecimal
        c.setPreco(valor);
    }//GEN-LAST:event_jftxtPriceCarneFocusLost

    private void btnAddCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCarneActionPerformed

    private void tblChurrascosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChurrascosMouseClicked
        // TODO add your handling code here:
        // Código para habilitar as outras abas assim que um churrasco for selecionado
        if (tblChurrascos.getSelectedRow() >= 0) {
            jTabbedPane1.setEnabledAt(1, true);
            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setEnabledAt(3, true);
        } else {
            jTabbedPane1.setEnabledAt(1, false);
            jTabbedPane1.setEnabledAt(2, false);
            jTabbedPane1.setEnabledAt(3, false);
        }
    }//GEN-LAST:event_tblChurrascosMouseClicked

    private void btnRemoveBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBebidaActionPerformed
        // TODO add your handling code here:
        // 0 = Botao 1 YES, 1 = Botao 2 NO
        if (JOptionPane.showConfirmDialog(null, "Deseja remover a bebida Churrasco?", "Confirmaçao",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
        // Obtém o Churrasco
        int linhaSelecionada = tblChurrascos.getSelectedRow();
        Churrasco churrasco = listChurrascos.get(linhaSelecionada);
        
        // Obtém o convidado do Churrasco
        int linhaBebidaSelecionada = tblBebidas.getSelectedRow();
        BebidaUtilizada bebidaUtilizada = churrasco.getBebidaUtilizada(linhaBebidaSelecionada);

        // Remove a associação entre churrasco e bebidaUtilizada
        churrasco.removeBebidaUtilizada(bebidaUtilizada);
        bebidaUtilizada.setChurrasco(null);

        entityManager.remove(bebidaUtilizada);
        
        // saveButton.doClick();
        
        atualizarTabelas(linhaSelecionada);        
        
    }

    }//GEN-LAST:event_btnRemoveBebidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBebida;
    private javax.swing.JButton btnAddCarne;
    private javax.swing.JButton btnAddConvidado;
    private javax.swing.JButton btnRemoveBebida;
    private javax.swing.JButton btnRemoveCarne;
    private javax.swing.JButton btnRemoveConvidado;
    private javax.swing.JComboBox<String> cbxBebidas;
    private javax.swing.JComboBox<String> cbxCarnes;
    private javax.swing.JComboBox cbxConvidados;
    private javax.swing.JButton deleteButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JFormattedTextField ftxtData;
    private javax.swing.JFormattedTextField ftxtHora;
    private javax.swing.JFormattedTextField ftxtQtde;
    private javax.swing.JFormattedTextField ftxtQtdeCarne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFormattedTextField jftxtPriceBebida;
    private javax.swing.JFormattedTextField jftxtPriceCarne;
    private javax.swing.JLabel jlbllogo;
    private javax.swing.JPanel jpnBebidas;
    private javax.swing.JPanel jpnButtons;
    private javax.swing.JPanel jpnChurrasco;
    private javax.swing.JPanel jpnConvidados;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIdchurrasco;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPriceCarne;
    private javax.swing.JLabel lblQtde;
    private javax.swing.JLabel lblQtde1;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblSelectBebida;
    private javax.swing.JLabel lblSelectCarne;
    private java.util.List<model.Bebida> listBebidas;
    private java.util.List<model.Carne> listCarnes;
    private java.util.List<model.Churrasco> listChurrascos;
    private java.util.List<model.Convidado> listConvidados;
    private javax.swing.JButton newButton;
    private util.PrecoRenderer precoRenderer1;
    private javax.persistence.Query queryBebida;
    private javax.persistence.Query queryCarne;
    private javax.persistence.Query queryChurrasco;
    private javax.persistence.Query queryConvidado;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPaneChurrasco;
    private javax.swing.JTable tblBebidas;
    private javax.swing.JTable tblCarnes;
    private javax.swing.JTable tblChurrascos;
    private javax.swing.JTable tblConvidados;
    private util.TimeRenderer timeRenderer1;
    private javax.swing.JTextField txtIdchurrasco;
    private javax.swing.JTextField txtLocal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadChurrasco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadChurrasco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadChurrasco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadChurrasco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog frame = new JDialog(new JFrame(), true);
                frame.setContentPane(new JCadChurrasco());
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

}
