/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author sigaln
 */
public class JFrmSplash extends javax.swing.JFrame {

    /**
     * Creates new form JFrmSplash
     */
    public JFrmSplash() {
        initComponents();

        /**
         * Este método é iniciado com o contrutor e trata a barra de progresso e
         * o carregamento do formulário de login
         */
        carregar();
    }
    
    // Implementaçao do método carregar
    public void carregar(){   
      
     ActionListener acao = (java.awt.event.ActionEvent e) -> {
          if (jProgressBar1.getValue() < 100) {
                jProgressBar1.setValue(jProgressBar1.getValue() + 2);
           } else {
               t.stop(); // parar a execuçao da barra de progressoz
              JFrmLogin login = new JFrmLogin(); // Instanciar formulário de login
              login.setVisible(true);
              this.setVisible(false); // ocultar este formulario Splash
           }
      };
       t = new Timer(50, acao);
       t.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        lblFogueira = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 350, 20));

        lblFogueira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_sistema_churrasco.png"))); // NOI18N
        getContentPane().add(lblFogueira, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(632, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrmSplash().setVisible(true);
        });
    }
    
    // Variável da classe Timer para controlar o tempo da barra de progresso
    private Timer t; 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblFogueira;
    // End of variables declaration//GEN-END:variables

}
